Video/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from . import views

app_name='music'

urlpatterns = [
    #/music/
    url(r'^$', views.index, name='index'),

    #/music/<album_id>/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    #/music/<album_id>/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

]

music/models.py
from django.db import models


# every class you create has to inherit from models.Model
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.artist + ' - ' + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    context = {
        'all_albums': all_albums,
    }
    return render(request, 'music/index.html', context)


def detail(request, album_id):
    #try:
    #    album = Album.objects.get(pk=album_id)

    #except Album.DoesNotExist:
    #    raise Http404("Album Doesnt Exist")
    album = get_object_or_404(Album, pk=album_id)

    return render(request, 'music/detail.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "You didn't Select anyOne",
        })

    else:
        selected_song.is_favorite = not selected_song.is_favorite
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">

    <div class="container-fluid">


        <!-- Header: so the logo in bootstrap is just called the navbar-header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!-- Items-->

        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="active   ">
                    <a href="{% url 'music:index' %}">

                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">

                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">

                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="" size="50">

                    <button type="button" class="btn btn.default">Search</button>
                </div>

            </form>

            <ul class="nav navbar-nav navbar-right">

                <li class="">
                    <a href="#">

                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">

                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        LogOut
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>

{% block body %}
{% endblock %}






</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{%  block title %}Album Details{% endblock %}

{% block body %}

    <img src="{{ album.album_logo }}">


    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>


    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>


    {% endif %}

    <form action="{% url 'music:favorite' album.id %}" method="post">
        {% csrf_token %}

        {% for song in album.song_set.all %}
            <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">

            <label for="song{{ forloop.counter }}">
                {{ song.song_title }}

                {% if song.is_favorite %}
                        <img src="https://i.imgur.com/b9b13Rd.png">
                {% endif %}

            </label><br>
        {% endfor %}

        <input type="submit" value="favorite">
    </form>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}


{% block body %}

    {% if all_albums %}
        <h2>Here are the List of Albums</h2>
        <ul>
            {% for album in all_albums %}
            <li>
                <a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a>
            </li>
            {% endfor %}
        </ul>
    {%  else %}
        <h3>You don't have any Albums</h3>

    {% endif %}

{% endblock %}